#ifndef _SPACEX_SPACEX_STATUS_H_
#define _SPACEX_SPACEX_STATUS_H_

#define SPACEX_SEPARATOR "$spacex_separator$"

#define SPACEX_MK_ERROR(x) (0x00000000 | (x))

typedef enum _spacex_status_t
{
    // Successed
    SPACEX_SUCCESS = SPACEX_MK_ERROR(0),
       
    // Work report
    SPACEX_BLOCK_HEIGHT_EXPIRED = SPACEX_MK_ERROR(0x2000),
    SPACEX_FIRST_WORK_REPORT_AFTER_REPORT = SPACEX_MK_ERROR(0x2001),
    SPACEX_WORK_REPORT_NOT_VALIDATED = SPACEX_MK_ERROR(0x2002),
    SPACEX_SERVICE_UNAVAILABLE = SPACEX_MK_ERROR(0x2003),
    
    // Failed
    SPACEX_MALLOC_FAILED = SPACEX_MK_ERROR(0x4000),
    SPACEX_SEAL_DATA_FAILED = SPACEX_MK_ERROR(0x4001),
    SPACEX_UNSEAL_DATA_FAILED = SPACEX_MK_ERROR(0x4002),
    SPACEX_BAD_SEAL_DATA = SPACEX_MK_ERROR(0x4003),
    SPACEX_SGX_FAILED = SPACEX_MK_ERROR(0x4004),
    SPACEX_NOT_EQUAL = SPACEX_MK_ERROR(0x4005),
    SPACEX_SGX_SIGN_FAILED = SPACEX_MK_ERROR(0x4006),
    SPACEX_SGX_VERIFY_SIG_FAILED = SPACEX_MK_ERROR(0x4007),
    SPACEX_UNEXPECTED_ERROR = SPACEX_MK_ERROR(0x4008),
    SPACEX_INVALID_MERKLETREE = SPACEX_MK_ERROR(0x4009),
    SPACEX_MALWARE_DATA_BLOCK = SPACEX_MK_ERROR(0x4010),
    SPACEX_OPEN_FILE_FAILED = SPACEX_MK_ERROR(0x4011),
    SPACEX_WRITE_FILE_FAILED = SPACEX_MK_ERROR(0x4012),
    SPACEX_DELETE_FILE_FAILED = SPACEX_MK_ERROR(0x4013),
    SPACEX_RENAME_FILE_FAILED = SPACEX_MK_ERROR(0x4014),
    SPACEX_MKDIR_FAILED = SPACEX_MK_ERROR(0x4015),
    SPACEX_ACCESS_FILE_FAILED = SPACEX_MK_ERROR(0x4016),
    SPACEX_INVALID_META_DATA = SPACEX_MK_ERROR(0x4017),
    SPACEX_INIT_QUOTE_FAILED = SPACEX_MK_ERROR(0x4018),
    SPACEX_SRD_NUMBER_EXCEED = SPACEX_MK_ERROR(0x4019),
    SPACEX_FILE_NUMBER_EXCEED = SPACEX_MK_ERROR(0x4020),
    SPACEX_DEVICE_ERROR = SPACEX_MK_ERROR(0x4021),
    SPACEX_OCALL_NO_ENOUGH_BUFFER = SPACEX_MK_ERROR(0x4022),

    // Json error
    SPACEX_JSON_ARRAY_ERROR = SPACEX_MK_ERROR(0x5001),
    SPACEX_JSON_OBJECT_ERROR = SPACEX_MK_ERROR(0x5002),
    SPACEX_JSON_STRING_ERROR = SPACEX_MK_ERROR(0x5003),
    SPACEX_JSON_BOOL_ERROR = SPACEX_MK_ERROR(0x5004),
    SPACEX_JSON_NULL_ERROR = SPACEX_MK_ERROR(0x5005),
    SPACEX_JSON_NUMBER_ERROR = SPACEX_MK_ERROR(0x5006),
    SPACEX_JSON_STARTING_ERROR = SPACEX_MK_ERROR(0x5007),

    // Persistence related
    SPACEX_PERSIST_ADD_FAILED = SPACEX_MK_ERROR(0x6001),
    SPACEX_PERSIST_DEL_FAILED = SPACEX_MK_ERROR(0x6002),
    SPACEX_PERSIST_SET_FAILED = SPACEX_MK_ERROR(0x6003),
    SPACEX_PERSIST_GET_FAILED = SPACEX_MK_ERROR(0x6004),

    // IAS report related
    SPACEX_IAS_QUERY_FAILED = SPACEX_MK_ERROR(0x7001),
    SPACEX_IAS_OK = SPACEX_MK_ERROR(0x7002),
    SPACEX_IAS_VERIFY_FAILED = SPACEX_MK_ERROR(0x7003),
    SPACEX_IAS_BADREQUEST = SPACEX_MK_ERROR(0x7004),
    SPACEX_IAS_UNAUTHORIZED = SPACEX_MK_ERROR(0x7005),
    SPACEX_IAS_NOT_FOUND = SPACEX_MK_ERROR(0x7006),
    SPACEX_IAS_UNEXPECTED_ERROR = SPACEX_MK_ERROR(0x7007),
    SPACEX_IAS_SERVER_ERR = SPACEX_MK_ERROR(0x7008),
    SPACEX_IAS_UNAVAILABLE = SPACEX_MK_ERROR(0x7009),
    SPACEX_IAS_INTERNAL_ERROR = SPACEX_MK_ERROR(0x7010),
    SPACEX_IAS_BAD_CERTIFICATE = SPACEX_MK_ERROR(0x7011),
    SPACEX_IAS_BAD_SIGNATURE = SPACEX_MK_ERROR(0x7012),
    SPACEX_IAS_BAD_BODY = SPACEX_MK_ERROR(0x7013),
    SPACEX_IAS_REPORTDATA_NE = SPACEX_MK_ERROR(0x7014),
    SPACEX_IAS_GET_REPORT_FAILED = SPACEX_MK_ERROR(0x7015),
    SPACEX_IAS_BADMEASUREMENT = SPACEX_MK_ERROR(0x7016),
    SPACEX_IAS_GETPUBKEY_FAILED = SPACEX_MK_ERROR(0x7017),
    SPACEX_SIGN_PUBKEY_FAILED = SPACEX_MK_ERROR(0x7018),
    SPACEX_GET_ACCOUNT_ID_BYTE_FAILED = SPACEX_MK_ERROR(0x7019),
    SPACEX_SWORKER_UPGRADE_NEEDED = SPACEX_MK_ERROR(0x7020),
    
    // Storage related
    SPACEX_STORAGE_SER_MERKLETREE_FAILED = SPACEX_MK_ERROR(0x8001),
    SPACEX_STORAGE_UPDATE_FILE_FAILED = SPACEX_MK_ERROR(0x8002),
    SPACEX_STORAGE_UNSEAL_FILE_FAILED = SPACEX_MK_ERROR(0x8003),
    SPACEX_STORAGE_UNEXPECTED_FILE_BLOCK = SPACEX_MK_ERROR(0x8004),
    SPACEX_STORAGE_NEW_FILE_NOTFOUND = SPACEX_MK_ERROR(0x8005),
    SPACEX_STORAGE_NEW_FILE_SIZE_ERROR = SPACEX_MK_ERROR(0x8006),
    SPACEX_STORAGE_EMPTY_BLOCK = SPACEX_MK_ERROR(0x8007),
    SPACEX_STORAGE_IPFS_BLOCK_GET_ERROR = SPACEX_MK_ERROR(0x8008),
    SPACEX_STORAGE_IPFS_CAT_ERROR = SPACEX_MK_ERROR(0x8009),
    SPACEX_STORAGE_IPFS_ADD_ERROR = SPACEX_MK_ERROR(0x8010),
    SPACEX_STORAGE_IPFS_DEL_ERROR = SPACEX_MK_ERROR(0x8011),
    SPACEX_STORAGE_FILE_DUP = SPACEX_MK_ERROR(0x8012),
    SPACEX_STORAGE_FILE_SEALING = SPACEX_MK_ERROR(0x8013),
    SPACEX_STORAGE_FILE_DELETING = SPACEX_MK_ERROR(0x8014),
    SPACEX_STORAGE_FILE_BLOCK_NOTFOUND = SPACEX_MK_ERROR(0x8015),
    SPACEX_STORAGE_NO_ENOUGH_SPACE = SPACEX_MK_ERROR(0x8016),
    SPACEX_STORAGE_INCOMPLETE_BLOCK = SPACEX_MK_ERROR(0x8017),

    // Validation related
    SPACEX_VALIDATE_GET_REQUEST_FAILED = SPACEX_MK_ERROR(0x9001),
    SPACEX_VALIDATE_HIGH_PRIORITY = SPACEX_MK_ERROR(0x9002),

    // Upgrade related
    SPACEX_UPGRADE_RESTORE_SRD_FAILED = SPACEX_MK_ERROR(0x10001),
    SPACEX_UPGRADE_RESTORE_FILE_FAILED = SPACEX_MK_ERROR(0x10002),
    SPACEX_UPGRADE_SEND_WORKREPORT_FAILED = SPACEX_MK_ERROR(0x10003),
    SPACEX_UPGRADE_INVALID_WORKREPORT = SPACEX_MK_ERROR(0x10004),
    SPACEX_UPGRADE_GET_BLOCK_HASH_FAILED = SPACEX_MK_ERROR(0x10005),
    SPACEX_UPGRADE_GEN_WORKREPORT_FAILED = SPACEX_MK_ERROR(0x10006),
    SPACEX_UPGRADE_WAIT_FOR_NEXT_ERA = SPACEX_MK_ERROR(0x10007),
    SPACEX_UPGRADE_BAD_SRD = SPACEX_MK_ERROR(0x10008),
    SPACEX_UPGRADE_BAD_FILE = SPACEX_MK_ERROR(0x10009),
    SPACEX_UPGRADE_IS_UPGRADING = SPACEX_MK_ERROR(0x10010),
    SPACEX_UPGRADE_NEED_LEFT_DATA = SPACEX_MK_ERROR(0x10011),
    SPACEX_UPGRADE_BLOCK_EXPIRE = SPACEX_MK_ERROR(0x10012),
    SPACEX_UPGRADE_NO_VALIDATE = SPACEX_MK_ERROR(0x10013),
    SPACEX_UPGRADE_RESTART = SPACEX_MK_ERROR(0x10014),
    SPACEX_UPGRADE_NO_FILE = SPACEX_MK_ERROR(0x10015),

    // For http
    SPACEX_HTTP_INVALID_INPUT = SPACEX_MK_ERROR(0x11001),
} spacex_status_t;

#endif /* !_SPACEX_SPACEX_STATUS_H_ */
